### ISSUE TITLE
Option to keep orignal assets urls

### ISSUE THREAD

**Issue by GarrisonBaird** [gildas-lormeau/SingleFileZ#31]
All the urls in original html are replaced, I wish there's an option to keep these urls
``` html
<img src="images/01.png" data-singlefilez-orignal-src="https://example.com/asdf.png">
<link rel="stylesheet" href="stylesheet_0.css" data-singlefilez-orignal-href="https://example.com/asdf.css"
```
Maybe js can be kept too, do a base64 encoding if security is considered
``` html
<![CDATA[<script>alert("hello")</script>]]>
```
> Thanks and happy new year!

**Comment by gildas-lormeau** [comment]
The original URLs can be found as comments of each entry in the zip file. Would this suffice?

**Comment by GarrisonBaird** [comment]
It would be complicated. If we want to get an original URL, we need to
- Find/build and import a zip library which has comment support
- Reload the original HTML/zip, pass it to zip library, and list all files with comments
- Build a map between zip comment, file path, and DOM node
If URLs are included in HTML, we can get it as easy as `element.dataset.originalSrc`

**Comment by gildas-lormeau** [comment]
I see, thank you for the detailed feedback. I will probably implement this feature as a hidden option which will be disabled by default.

**Comment by gildas-lormeau** [comment]
I did some tests and I realize that this feature is harder to implement than expected. I need to see how I can add these URLs in CSS easily.

**Comment by GarrisonBaird** [comment]
In CSS there are two approaches, one is using comments:
``` css
body {
  background-image: url("singlefilez.png");
  /* background-image: url("htpps://example.com/singlefilez.png") */
}
```
another is using [CSS custom properties](https://developer.mozilla.org/en-US/docs/Web/CSS/--*):
``` css
body { 
  background-image: url("singlefilez.png");
  --singlefilez-background-image: url("htpps://example.com/singlefilez.png");
}
```
